#!/usr/bin/env bash
# a script that install nginx web server and configures it.

sudo apt-get -y install nginx
sudo chown "$USER":"$USER" /var/www/html/
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
