#!/usr/bin/env bash

# Define the configuration file path
config_file="/etc/nginx/sites-available/default"

# Define the block to be added
redirect_block="
        location /redirect_me {
                # redirect to https://www.youtube.com/watch?v=QH2-TGUlwu4
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}"

# Check if the block already exists in the configuration file
if grep -q "location /redirect_me" "$config_file"; then
    echo "Redirect block already exists. Skipping..."
    exit 0
fi

# Add the block using sed
#sed -i "/server_name _;/a $redirect_block" "$config_file"
sudo sed -i "/server_name _;/r /dev/stdin" "$config_file" <<< "$redirect_block"


# Restart Nginx to apply the changes
sudo service nginx stop
sudo service nginx start

echo "Redirect block added successfully."
