#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# install haproxy
sudo apt-get -y install update
sudo apt-get -y install haproxy

# hostnames of server

# configure haproxy
config_file="/etc/haproxy/haproxy.cfg"
config_text="
frontend frontends
        bind *:80
        mode http

        default_backend servers

backend servers
        balance roundrobin
        server server1 54.144.251.105
        server server2  54.90.53.190"

# apply configuration
# check if block exists before appending
if grep -q "default_backend servers" "$config_file"; then
    echo "Block already exists. Skipping..."
    exit 0
fi
echo "$config_text" | sudo tee -a "$config_file"

# for haproxy to be initialized with init
config_file="/etc/default/haproxy"

# check if line exist before appending
if grep -q "ENABLED=1" "$config_file"; then
    echo "Line already exists. Skipping..."
    exit 0
fi
echo "ENABLED=1" | sudo tee -a "$config_file"

# start haproxy
sudo service haproxy start
