#!/usr/bin/env bash
# This script fresh install mysql5.7
# remember to select bionic in the first prompt

sudo wget -O mysql57 https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57 && sudo chmod +x mysql57 &&  sudo ./mysql57
