#!/usr/bin/env bash
# pings an IP address passed as an argument

num_args="$#"
file_name="$(basename $0)"
ip_address="$1"

if [ "$num_args" -eq 0 ]
then
	echo "Usage: $file_name {IP_ADDRESS}"
else
	"$(ping -c 5 $ip_address)"
fi
