#!/usr/bin/env bash
# displays numbers from 1 to 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

for number in {1..100}
do
	if [ $((number % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	
	elif [ $((number % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((number % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$number"
	fi
done	
