#!/usr/bin/env bash
# This script is displaying "Best School" 9 times
# on the 9th times it will display Hi

i=0
while ((i <= 10))
do
	if [ $i = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	((i++))
done
