#!/usr/bin/env bash
# 12 hours clock

hours=12
hour=0

while [ "$hours" -ge 0 ]
do
	minutes=1
	echo "Hour: $hour"
	while [ "$minutes" -le 60 ]
	do
		if [ $minutes -eq 60 ]
		then
			((hour++))
		else
			echo "$minutes"
		fi
		((minutes++))
	done

	((hours--))
done
