#!/usr/bin/env bash
# this script install apache2

# install apache2
sudo apt update
sudo apt-get install apache2

# configure apache2
file="/var/www/html/index.html"
file_copy="/var/www/html/xzy"

sudo touch "$file_copy"
sudo cp "$file" "$file_copy"
echo "Hello Holberton" | tee "$file" > /dev/null

sudo service apache2 start
